package question3;

import java.util.Random;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        //this code block generates a random number between 1 and 100
        Random rnd = new Random();

        int actual = rnd.nextInt(99)+1;

        System.out.println(actual);

        //this code block asks the user to guess this number
        Scanner in = new Scanner(System.in);


        boolean win = false;
        //this code block gives the user feedback
        for (int i = 0; i<10; i++) {

            System.out.println("Please guess the actual number generated by the program");
            int user = in.nextInt();

            if( user>actual ) {
                if ( user-actual>=50 ) {
                    System.out.println("Your number is much higher than the actual number");
                }
                else System.out.println("Your number is higher than the actual number");
            }
            else if ( user<actual ) {
                if ( actual-user>=50 ) {
                    System.out.println("Your number is much lower than the actual number");
                }
                else System.out.println("Your number is lower than the actual number");
            }
            else if (user == actual) {
                System.out.println("Your number is equal to the actual number");
                win = true;
                break;
            }
        }


        if (win == true) {
            System.out.println("Congratulations you won");
        }
        else if (win == false) {
            System.out.println("Sorry you have run out of turns");
        }
    }
}
